hook-tests/008-etc-writable.test
hook-tests/024-configure-bootchart.test
hooks/001-extra-packages.chroot
hooks/008-etc-writable.chroot
hooks/024-configure-bootchart.chroot

Missing commits from core20 repo.

Sync with core20

---

.github/workflows/test.yaml
hooks/001-extra-packages.chroot
tests/spread/basic/task.yaml

Fixes https://github.com/snapcore/core-base/issues/22

hooks: add systemd-timesyncd

---

static/usr/bin/core-sshd-host-keygen

removing perl dependency from base snap
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

static: remove perl dependency

---

Makefile
snapcraft.yaml

probert: from git instead of archive

---

hooks/001-extra-packages.chroot
hooks/400-trim-pkcs-11.chroot

Add pkcs11 dependencies into core20 base snap

core: add pkcs11 dependencies

---

static/usr/lib/systemd/system/fix-hctosys.service
static/usr/lib/udev/rules.d/90-fix-hctosys.rules

Fixes https://bugs.launchpad.net/baoshan/+bug/1987724

Trigger fix-hctosys through systemd instead of directory in udev

---

.github/workflows/tests.yaml

[core22] Fix release branch selection in workflow for pull/push

---

hooks/001-extra-packages.chroot
hooks/200-enable-pwquality.chroot
static/etc/system-image/writable-paths

Same with the one from UC20 repo, https://github.com/snapcore/core20/pull/140

Allow to update password policy

---

static/usr/lib/udev/rules.d/71-nvidia.rules

These integrate nvidia graphics cards with logind and enable power management.

static: add generic nvidia udev rules

---

README.md
hook-tests/014-set-motd.test
hooks/000-provide-uids-gids.chroot
hooks/001-extra-packages.chroot
hooks/011-patch-ext4-conf.chroot
hooks/014-set-motd.chroot
hooks/900-cleanup-etc-var.chroot
snapcraft.yaml
spread.yaml
static/etc/issue
static/etc/issue.net
tests/lib/nested.sh
tests/lib/prepare-utils.sh
tests/spread/ci/build-image/task.yaml

~~Depends on https://github.com/snapcore/snapcraft/pull/4068~~

Use build-base devel

---

snapcraft.yaml

Picking recent changes from subiquity

snapcraft.yaml: update subiquity version

---

hook-tests/028-remove-systemd-tpm2-setup.test
hooks/028-remove-systemd-tpm2-setup.chroot

Fixes part of https://github.com/snapcore/core-base/issues/195

hooks: remove systemd-tpm2-setup

---

static/usr/lib/tmpfiles.d/journald-conf-d.conf

Core22 version of https://github.com/snapcore/core-base/pull/200

static/usr/lib/tmpfiles.d: create journald config drop-in directory

---

snapcraft.yaml

snapcraft.yaml: move or remove extra files from plymouth theme

---

tests/lib/prepare-utils.sh

We have to keep the model file in this repo until core-initrd is updated.

tests: use model from models repository

---

static/usr/lib/systemd/system/emergency-reboot.service
static/usr/lib/systemd/system/emergency.service.d/core-override.conf
static/usr/lib/systemd/system/emergency.target.d/core-override.conf
static/usr/lib/systemd/system/emergency.target.wants/emergency-reboot.service

This is a backport of https://github.com/snapcore/core-initrd/pull/124
Will "undraft" it after I have tested it. I opened it to remember.

emergency: wait for 10 seconds before rebooting

---

hooks/009-locale-archive.chroot
static/etc/system-image/writable-paths

This is read by pam and others.

hooks: create locale configuration 

---

hooks/000-provide-uids-gids.chroot
hooks/001-extra-packages.chroot
static/usr/lib/tmpfiles.d/coredump-comf-d.conf

This is https://github.com/snapcore/core-base/pull/199 plus a commit to create a configuration folder.

hooks,static: add support for systemd-coredump

---

Makefile
hooks/032-apply-patches.chroot
patch/netplan-apply.diff

See also https://github.com/canonical/netplan/pull/449

Change netplan apply to workaround LP#2058976

---

Makefile
hooks/603-cleanup-docs.chroot
snapcraft.yaml
tools/generate-changelog.py

Forward port of https://github.com/canonical/core-base/pull/234

snapcraft,make(main): add script for generating changelogs, include as part of build

---

Makefile
snapcraft.yaml
tools/generate-changelog.py

Backport of https://github.com/canonical/core-base/pull/234

snapcraft,make(core22): add script for generating changelogs, include as part of build

---

Makefile
tools/generate-changelog.py

Example of changelog with this change: https://paste.ubuntu.com/p/qcyYNVwMXz/

many: introduce changelog for the snap repository itself prior to package changes

---

snapcraft.yaml

Update console-conf so it includes
https://github.com/canonical/subiquity/pull/2071.

snapcraft.yaml: update console-conf

---

hooks/001-extra-packages.chroot

- Add openssh to install the fips-variant ssh
- The normal openssh has issue to work properly with fips kernel snap

FIPS packages: Replace existing packages with meta package

---

hooks/001-extra-packages.chroot

Hooks: Avoid confirmation prompt from installing base-files or any other pkgs

---

SECURITY.md

When approved, will be ported to `core24` and `main` branches

SECURITY.md: add our security policy

---

hooks/009-locale-archive.chroot
hooks/010-locale-vconsole-symlinks.chroot
static/etc/system-image/writable-paths

See the LP bug for more information, along with test results of this change: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2091657
The test results are in this comment: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2091657/comments/2

hooks,static: make /etc/vconsole.conf and /etc/locale.conf symlinks to writable

---

SECURITY.md

Propose for core24
Backport of https://github.com/canonical/core-base/pull/328

SECURITY.md: add our security policy (core24)

---

SECURITY.md

SECURITY.md: add our security policy (main) 

---

tools/generate-changelog.py

core22 version of https://github.com/canonical/core-base/pull/345

tools: aggregate old changelogs

---

.github/workflows/release.yaml
get-version.sh
snapcraft.yaml

For the moment it will be started manually.

.github/workflows/release.yaml: add release job

---

.github/workflows/tests.yaml
static/usr/lib/systemd/system/plymouth-quit.service.d/core-override.conf
static/usr/lib/systemd/system/plymouth-show-install.service
static/usr/lib/systemd/system/plymouth-show-run.service
static/usr/lib/systemd/system/secureboot-db.service.d/core-override.conf
static/usr/lib/systemd/system/snapd.autoimport-device@.service
static/usr/lib/systemd/system/splash-client.service
tests/lib/prepare-uc.sh

Backport of https://github.com/canonical/core-base/pull/353

many: fix the way the mode is being checked

---

get-version.sh
snapcraft.yaml

Use date tag if present to set the version, otherwise use current date. This backports changes done for core24.

many: ser snap version from date tag if present
