- Makefile
The devel tarballs have a different path than tarballs from already released series. This is why originally, in my previous PR, there was the whole DEVEL instead of LTS magic.
We could just change the url, but I think this way it is much more clear that this is completely temporary.
> Properly use the devel series for the base tarballs

- snapcraft.yaml
This seems to have been reverted after the force push.
I am still not sure if we'll manage to get the builds working. It's hard for me to make launchpad use impish for the snap recipe build, and infering from snapcraft.yaml might not work. This is very annoying and very counterproductive so far.
> Fix snapcraft.yaml to build core22 instead of core20

- snapcraft.yaml
This seems to be the final bit required to get the new core22 snap building.
Since in Launchpad it's not possible to select 'Impish' as the series, and we need to build on impish because we no longer build daily tarballs of hirsute, we need to rely on LP's ability to guess the series from snapcraft.yaml. It seems LP does that guessing per `build-base:`. Now that LP recognizes core22 as a base (albeit still a devel one), we can switch to using it as the 'build-base' and make the builders acknowledge that we need to use Impish.
Ran a test build via a separate snap build recipe and it seems to build successfully:
https://launchpad.net/~sil2100/snap-core22/+snap/core22
> Use build-base: core22 for LP to recognize Impish as the build platform.

- hook-tests/001-extra-packages.test
in impish, libffi package name is simply libffi8
fixing this to let lp build correctly
> fix libffi version for impish

- snapcraft.yaml
This should fix the core22 builds on impish. We need to remember to remove this workaround once we have the current edge snapd version in stable.
> Add a temporary hack to use the edge snapd for core22

- hooks/000-provide-uids-gids.chroot
- hooks/990-ensure-uids-gids.chroot
Now that I understand the situation, switch back to guarding against a GID 113 and move the sgx to a new free GID. Big thanks to mvo for catching this mistake!
> Fix provided group IDs in core22

- Makefile
- snapcraft.yaml
This is mostly just a formality, since we already build using the current 'devel' tarball (as jammy is not out yet) - so we're pulling in the jammy tarball now anyway.
Note for the future: we might want to revisit some of the core20 hacks that are present in snapcraft.yaml and see if those are still relevant.
> Switch to jammy, and remove some core20 references.

- Makefile
- hook-tests/001-extra-packages.test
- hook-tests/600-no-debian.chroot
- hooks/600-no-debian.chroot
I'm not actually able to build this snap as I was for core, core18 or core20.
I'm getting a multipass error: " launch failed: Unable to find an image matching "core22". An error occurred with the instance when trying to launch with 'multipass': returned exit code 2. Ensure that 'multipass' is setup correctly and try again."
I'm using snapcraft version 5.0 and multipass  1.7.1.
It would be ideal if I could build locally to see if the list of packages in the unit test is  correct for core22.
> Generate dpkg.yaml for OSS compliance

- README.md
- hook-tests/024-configure-bootchart.test
- hooks/001-extra-packages.chroot
- hooks/024-configure-bootchart.chroot
Add configuration files so it is possible to get a bootchart on
boot. The systemd-bootchart.service will not be enabled by default,
but it will be possible to enable it from kernel command
line (systemd.wants=systemd-bootchart.service) if we want it to run on
first boot.
> Add bootchart configuration

- hook-tests/020-extra-files.test
- hooks/020-extra-files.chroot
- static/etc/systemd/system.conf.d/11-snapd-ctrl-alt-del-burst.conf
Systemd provides two ctrl-alt-del keyboard hooks (enabled by default)
exposing Ubuntu Core to malicious reboot request attacks.
(1) Ctrl-alt-del single press
(2) Ctrl-alt-del burst (7 presses or more in 2 seconds)
These issues are acknowledged and one addressed in a systemd commit
(commit: 24dd31c19ede505143833346ff850af942694aa6, 231 and later) by providing
a config item for the systemd manager to disable the ctrl-alt-del burst action.
Issue (1) is addressed in snapd by allowing the ctrl-alt-del.target to be
masked (pull: https://github.com/snapcore/snapd/pull/11113)
Issue (2) is addressed in this patch by disabling burst action in the systemd
manager config using a drop-in configuration file.
Testing: The ctrl-alt-del kernel sequence sends a SIGINT to PID1 (systemd).
The burst sequence …
> static: disable systemd ctrl-alt-del burst action

- Makefile
- hooks/001-extra-packages.chroot
- hooks/013-add-mdns-hostname-resolution.chroot
- snapcraft.yaml
In jammy, nss-mdns has downgraded avahi-daemon from Depends to
Recommends, thus one can simply install libnss-mdns without recommends
to avoid including avahi-daemon.
Link: https://launchpad.net/ubuntu/+source/nss-mdns/0.15.1-1ubuntu1
> Drop avahi-daemon-equiv-deb

- hooks/001-extra-packages.chroot
- hooks/600-no-debian.chroot
We now have a new HTTPS-capable domain for public PPAs, namely
ppa.launchpadcontent.net.  Adjust various bits of the build system to
accept that.
> Handle PPAs being served from ppa.launchpadcontent.net

- hook-tests/014-set-motd.test
- hooks/014-set-motd.chroot
- hooks/018-set-os-release.chroot
- hooks/024-configure-bootchart.chroot
- hooks/900-cleanup-etc-var.chroot
- hooks/901-cleanup-timesyncd.chroot
- static/etc/issue
- static/etc/issue.net
- static/usr/lib/core/handle-writable-paths
While creating some test-snapd-*-core22 snaps I noticed that
the core22 has some outdated /etc/os-release date. This
commit fixes this.
> many: change [Cc]ore\ *20 -> [Cc]or\ *22

- hook-tests/016-ensure-bootloaders.test
- hooks/016-ensure-bootloaders.chroot
This will be needed when https://github.com/snapcore/snapd/pull/11068 is merged.
> hooks: create mount point for piboot bootloader

- hooks/020-extra-files.chroot
Snaps using the cups interface with the cups snap as of snapd 2.55 will create
a bind mount of /run/cups -> /var/cups, which since /var/cups does not exist
will trigger the writable mimic code to create a writable mimic on /var. This
results in a fair amount of extra bind mounts for every directory in /var, so
creating this directory empty in the base snap ensures that no writable mimic
need be created.
Note that this will result in review-tools complaining when this is merged and a
new core22 is uploaded since a new directory is being added to the base snap,
but this is okay.
> hooks: mkdir /var/cups to avoid writable mimic creation for snaps using cups

- hooks/001-extra-packages.chroot
- hooks/012-add-foreign-libc6.chroot
Do not install recommendations when installing libc6 for foreign
architectures and for installing the locally built console-conf and
friends, as this was installing a significant amount of packages that
we do not want in the base.
The now removed packages are:
gir1.2-glib-2.0:amd64
krb5-locales
libcom-err2:i386
libgirepository-1.0-1:amd64
libgssapi-krb5-2:i386
libidn2-0:i386
libk5crypto3:i386
libkeyutils1:i386
libkrb5-3:i386
libkrb5support0:i386
libnsl2:i386
libnss-nis:i386
libnss-nisplus:i386
libssl3:i386
libtirpc3:i386
libunistring2:i386
python3-gi
> hooks: use --no-install-recommends in all installations

- static/usr/lib/systemd/system/snapd.autoimport-device@.service
- static/usr/lib/udev/rules.d/66-snapd-autoimport.rules
`snap auto-import` cannot run anymore because of sandboxing of
systemd-udevd. Instead we need to schedule a systemd service.
~~It could be an issue for users using udisks2, where a logged in user
would automatically mount disks marked as `UDISKS_AUTO`. For a short
time, snap could have mounted the device and udisks might fail to
mount.  For this reason we introduce `SNAP_AUTO_IMPORT` so that users
can introduce a custom udev rule to disable auto import on devices
(all or filtered).~~
> Stop running auto-import directly from udevd

- snapcraft.yaml
The `ensures: [snapd-2.55.5]` ensures that we have a version of
snapd that will *not* migrate ~/snap -> to ~/Snap for core22
using snapd.
Snapd 2.55.x before 2.55.5 would automatically create a
~/Snap/<snapname> folder for all the snaps that use `base: core22`.
However this is not what we want so to ensure this will not
happen we ensure that all the snapd versions used with core22 are
at least 2.55.5.
> snapcraft: add `assumes: [snapd2.55.5]`

- hooks/101-do-not-print-issue.chroot
console-conf upstream service already has `-i`, so now we were adding
it a second time.
> hooks: remove hook working around missing parameter to agetty

- snapcraft.yaml
`consoleconf-deb` does not need to rebuild if `probert-deb` was
changed.
> snapcraft.yaml: Fix part dependencies

- snapcraft.yaml
Not moving this to a tag yet, as this fix is console-conf specific.
Picks up https://github.com/canonical/subiquity/pull/1310
> console-conf: update commit for LP: #1978339

- hook-tests/029-fix-ld-so-symlink.test
- hooks/029-fix-ld-so-symlink.chroot
Just some pedantic changes
- Use bash syntax
- Disallow undefined variables
- Do not assume there is no space in paths (though unlikely)
- Do not assume that the symlinks have a specific path depth
- Ignore non symlinks (still fail in test)
- Show all errors in the test instead of exiting on first error
> hooks: Improve robustness of fix-ld-so-symlink hook

- Makefile
- build-package.sh
- hooks/001-extra-packages.chroot
- snapcraft.yaml
* Use stage area to provide packages across snapcraft parts instead of
using `$(CRAFT_PART_INSTALL)/../..`
* Make a local debian package repository
* Send all built binary packages to `extra-packages` hook. This is to
avoid version mismatch in case some dependency start requiring other
built packages
* Install all extra packages at once
> Refactor extra-packages hook

- snapcraft.yaml
The mirrors use a round robin on `cdimage.ubunutu.com`. So calling
wget multiple times might resolve to different mirrors that might be
out of sync. Instead we need to call wget once to download all the
files.
> Fix downloading of base image when mirrors are not in sync

- Makefile
Variable `f` is not defined. So it is not going to print anything
interesting.
> Makefile: remove a forgotten debug print

- static/usr/lib/core/handle-writable-paths
- static/usr/lib/systemd/system/local-fs.target.requires/var-lib-snapd-save.mount
- static/usr/lib/systemd/system/var-lib-snapd-save.mount
- tests/spread/main/basic/task.yaml
As a part of the customer request to have a per-snap folder on the ubuntu-save partition, and because we do not want to expose the /run/mnt path to apparmor, we instead mount ubuntu-save into /var/lib/snapd as 'save'. This is already done by snap, but this happens to late in the startup process, and would create a dependency between snaps and snapd.
> static/usr/lib/core: mount ubuntu-save to /var/lib/snapd/save

- Makefile
When there is no RTC systemd will use either it's own build date
or `/usr/lib/clock-epoch` to "seed" the initial time. So far we
did not create /usr/lib/clock-epoch but this commit adds it.
Forward-ported from
https://github.com/snapcore/core20/commit/ba61659045c4458175ef828f20f3a80fc62ee6db
> Makefile: create /usr/lib/clock-epoch

- static/usr/lib/core/fix-hctosys
- static/usr/lib/udev/rules.d/90-fix-hctosys.rules
When the system has a RTC that is loaded as a module the time
may move backwards when the rtc module is loaded. See
https://forum.snapcraft.io/t/30391/15
This is a (racy) workaround to fix this.
See also the upstream bug:
https://github.com/systemd/systemd/issues/17737
Forward-ported from https://github.com/snapcore/core20/commit/ba0e938c8716e8852c052e0a572e6b2b9e0d0fc0
> static: add fixrtc script and udev.rules (#136)

- hooks/001-extra-packages.chroot
- hooks/026-configure-plymouth.chroot
- snapcraft.yaml
- static/usr/bin/splash-client
- static/usr/lib/systemd/system/plymouth-halt.service.d/core-override.conf
- static/usr/lib/systemd/system/plymouth-kexec.service.d/core-override.conf
- static/usr/lib/systemd/system/plymouth-poweroff.service.d/core-override.conf
- static/usr/lib/systemd/system/plymouth-quit.service.d/core-override.conf
- static/usr/lib/systemd/system/plymouth-reboot.service.d/core-override.conf
- static/usr/lib/systemd/system/plymouth-show-factory-reset.service
- static/usr/lib/systemd/system/plymouth-show-install.service
- static/usr/lib/systemd/system/plymouth-show-recover.service
- static/usr/lib/systemd/system/plymouth-show-run.service
- static/usr/lib/systemd/system/plymouth-start.service.d/core-override.conf
- static/usr/lib/systemd/system/splash-client.service
Adds configuration to the base for splash screen. This requires also initramfs changes. Just a draft for the moment as we need a new plymouth deb package in jammy and some snapd changes.
> many: add configuration for splash screen

- hook-tests/031-faillock.test
- hooks/031-faillock.chroot
- static/usr/lib/core/lockout-not-enabled.sh
- static/usr/share/pam-configs/optional-lockout
- static/usr/share/pam-configs/optional-lockout-authsucc
- static/usr/share/pam-configs/optional-lockout-preauth
- static/usr/share/pam-configs/snappy-extrausers
When `/etc/writable/faillock.enabled` is present, then we use `pam_faillock` which can lock accounts for 900 seconds after 3 wrong password.
Can be tested with `faillock --user username`. Also use `faillock --user username --reset` instead of waiting 900 seconds.
Requires https://github.com/snapcore/snapd/pull/12278
> pam: add optional faillock

- hooks/050-snap-symlink.chroot
Completion for `snap` must be present in
`/usr/share/bash-completion/completions/` and it must point to the
file in the active Snapd.
Other completion will be added in
`/var/lib/snapd/desktop/bash-completion/completions/` by Snapd. To be
able to access those `XDG_DATA_DIRS` has to be set by Snapd's
`profile.d` file.
This commits also adds snap's `environment.d` file which is used
by user services rather than interactive users.
This depends on snapcore/snapd#11038
> hooks: Add symlinks for bash completions of snap and snaps

- static/usr/lib/systemd/system/keep-entangled-mounts.target
- static/usr/lib/systemd/system/remount-data.service
- static/usr/lib/systemd/system/remount-seed.service
- static/usr/lib/systemd/system/run-mnt-data.mount.d/late-umount.conf
- static/usr/lib/systemd/system/run-mnt-kernel.mount.d/late-umount.conf
- static/usr/lib/systemd/system/run-mnt-ubuntu\x2dseed.mount.d/late-umount.conf
- static/usr/lib/systemd/system/shutdown.target.wants/keep-entangled-mounts.target
- static/usr/lib/systemd/system/shutdown.target.wants/remount-data.service
- static/usr/lib/systemd/system/shutdown.target.wants/remount-seed.service
- static/usr/lib/systemd/system/usr-lib-modules.mount.d/late-umount.conf
Because `/` is a squashfs from `/run/mnt/data`, we cannot unmount `/run/mnt/data`. (Or `/run/mnt/ubuntu-seed` during install/recovery).
So we need to disable `/run/mnt/data` by adding it to `shutdown.target`. However we need also to remount read-only. To avoid with writable bind mounts, we need to do it after `umount.target`.
This does not remove errors from finalrd which will be fixed in a different PR.
Note for testing: this happens after journald has stopped writing to logs. So you need to use serial port to properly log the errors.
> Remove some unmounting errors on shutdown

- hook-tests/902-cleanup-polkit.test
- hooks/902-cleanup-polkit.chroot
Since we do not distribute the polkit daemon, those files are useless.
> Remove polkit policies and rules

- static/usr/lib/systemd/system/snapd.sshd-keygen.service
The correct name is `ssh.service`
> snapd.sshd-keygen.service: fix unit dependency to sshd

- hooks/101-systemd-fsck.chroot
- static/usr/lib/systemd/system/keep-entangled-mounts.target
- static/usr/lib/systemd/system/shutdown.target.wants/keep-entangled-mounts.target
- static/usr/lib/systemd/system/system-systemd\x2dfsck.slice
Some mounts cannot be unmounted during `shutdown.target`.  We have tried make them part of `shutdown.target` so they are kept alive. But because they depend on `system-systemd\\x2dfsck.slice` and `systemd-fsck@.service` which both conflict with `shutdown.target`, it confuses systemd, and the result of what gets scheduled is not deterministic.
Instead we remove conflicts of `system-systemd\\x2dfsck.slice` and `systemd-fsck@.service`. Then `DefaultDependencies=no` on mounts is enough to disable unmounts.
> Rework disabling of unmounts

- hook-tests/001-extra-packages.test
- hooks/001-extra-packages.chroot
The security team maintains a PPA with the user-space parts of cryptsetup support for the Inline Crypto Engine (ICE) code.
This needs to be included in the core build so that FDE on ICE is supported.
The full ICE implementation uses:
https://github.com/chrisccoulson/linux/tree/dm-blk-crypto https://github.com/chrisccoulson/cryptsetup/tree/ice-wip
and is getting upstreamed by the kernel and security teams.
> [Core22] hooks: include ppa:ubuntu-security/fde-ice as part of the builds

- hook-tests/009-locale-archive.test
- hooks/001-extra-packages.chroot
- hooks/009-locale-archive.chroot
This is needed for `ln_langinfo(CODESET)` to return the right encoding.
This adds around 750K in size.
It fixes https://github.com/fwupd/fwupd/issues/5484
> Make all supported locale aliases to C

- static/usr/lib/udev/rules.d/90-fix-hctosys.rules
Backport fix https://github.com/snapcore/core-base/pull/121 from branch main to core22.
> static: correct service name used in hctosys rtc fix rule

- static/usr/lib/core/fix-hctosys
Correct CLOCK_EPOCH.
This change is backported from main: https://github.com/snapcore/core-base/pull/125
> static: correct clock epoch file in script fix-hctosys

- hook-tests/001-extra-packages.disabled
- hooks/001-extra-packages.chroot
The security team maintains a PPA with the user-space parts of cryptsetup support for the Inline Crypto Engine (ICE) code.
This needs to be included in the core build so that FDE on ICE is supported.
The full ICE implementation uses:
https://github.com/chrisccoulson/linux/tree/dm-blk-crypto https://github.com/chrisccoulson/cryptsetup/tree/ice-wip
and is getting upstreamed by the kernel and security teams.
(draft to see if CI is happy)
> hooks: include ppa:ubuntu-security/fde-ice as part of the builds

- hook-tests/027-remove-pcrphase.test
- hooks/027-remove-pcrphase.chroot
pcrphase depends on a library that we do not provide. Since we do not use PCR 11, we can drop it for now.
> Remove pcrphase

- static/usr/libexec/core/get-arg
Anything with and "A" or a "0" in the name was not parsed correctly and interpreted as a space instead.
> get-arg: fix call to printf

- hooks/027-remove-pcrphase.chroot
On s390x, systemd-pcrphase is not installed.
> Do not fail when pcrphase files do not exist

- README.md
- static/usr/lib/systemd/system-generators/bootchart
in the kernel command line, instead of core.bootchart.
> Trigger bootchart if ubuntu_core.bootchart is set

- README.md
- static/usr/lib/systemd/system-generators/bootchart
To keep consistency with other kernel command line settings.
> Accept ubuntu_core.bootchart as alias for core.bootchart

- static/usr/lib/core/rtc-sys-time-init
- static/usr/lib/udev/rules.d/90-rtc-sys-time-init.rules
This is cherry-pick of https://github.com/snapcore/core20/pull/156
Two optimization here:
* We filter IMPORT{cmdline}. This causes some system calls. On core20, it also reads UEFI variables. This is very slow. We used to read the cmdline on all device. Now we do it only on rtc devices.
* We stop calling /usr/bin/systemd-escape.
The first optimization is the most effective part. On google cloud, we reduce the time to cold boot devices from around 30s to 4s.
> 90-rtc-sys-time-init.rules: Optimize

- hooks/000-provide-uids-gids.chroot
- hooks/001-extra-packages.chroot
- hooks/602-cleanup-xml-core.chroot
- static/etc/system-image/writable-paths
polkit is needed in some cases for communication between services shipped in the base, for instance when systemd-networkd talks to systemd-hostnamed to set the hostname. Enable to fix these use cases. Note that this does not help yet if we want to use it from a snap.
> hooks: enable polkit for unconfined processes

- static/usr/lib/udev/rules.d/66-snapd-autoimport.rules
Because we might run `snap auto-import --mount` on a partition table block and its partition blocks at the same time, it might cause a conflict.  We then get an error like `/dev/sda1 already mounted or mount point busy.`.
To go around this issue, we trigger the service only for devices that are identified as filesystems.
> 66-snapd-autoimport.rules: filter out non filesystem blocks

- hook-tests/027-remove-pcrphase.test
- hooks/027-remove-pcrphase.chroot
This runs `systemd-pcrphase` which we do not use and we have removed.
> Remove systemd-pcrmachine.service

- static/usr/lib/systemd/system/snapd.autoimport-device@.service
There is a conflict between snapd.autoimport.service and snapd.autoimport-device@.service. This causes error messages because both cannot mount in the same time. So they cannot be run at the same time.
> snapd.autoimport-device@.service: do not run along snapd.autoimport.service

- spread.yaml
Switch snapcraft to latest/edge to get the fix for https://bugs.launchpad.net/snapcraft/+bug/2051567
> spread: switch snapcraft to latest/edge

- hooks/606-cleanup-xkb.chroot
Drop xkb data files.
Based on #176 
AMD64 core24 size is reduced by 1124kB wrt. the snap obtained from #176, 2728kB in total vs current upstream.
Fixes #178
> hooks: remove xkb data

- snapcraft.yaml
snapcraft now complains of `CRAFT_TARGET_ARCH` now being deprecated.
> snapcraft.yaml: use CRAFT_ARCH_BUILD_FOR instead of CRAFT_TARGET_ARCH

- hooks/040-remove-pkgs.chroot
file is added as a dependendency of cracklib-runtime. However we already drop all the binary programos of cracklib-runtime package and only leave the cache files, hence file becomes non-essential. The libmagic dependency of file pulls in libmagic-mgc carrying a 8MB+ binary file with file identification data.
Saves ~500kB on the snap size.
> hooks: remove file, libmagic and its data

- hooks/300-remove-pkgs-late.chroot
- hooks/606-cleanup-perl.chroot
This PR drops perl-base and adduser from the base.
Size is reduced 2.2MB
> hooks: remove perl-base and adduser

- static/usr/lib/core/run-snapd-from-snap
Needed by https://github.com/snapcore/snapd/pull/13370
> run-snapd-from-snap: set the current symlink before bootstrapping

- hooks/601-clean-cracklib.chroot
chpasswd fails when the cracklib_dict.pwd is gzipped
```
echo test:ubuntu123 | sudo chpasswd
/var/cache/cracklib/cracklib_dict.pwd: No such file or directory
BAD PASSWORD: The password fails the dictionary check - error loading dictionary
```
without gzipping:
```
ubuntu@localhost:~$ echo ubuntu:my-long-username-password | sudo chpasswd
ubuntu@localhost:~$ 
```
We used to gzip it because of passwd looking for it with a gz extension (https://github.com/snapcore/core20/issues/143). But not gzipping it works for passwd:
```
ubuntu@localhost:~$ passwd ubuntu
Changing password for ubuntu.
(current) UNIX password: 
New password: 
Retype new password: 
passwd: password updated successfully
```
> hooks: dont gzip cracklib pwd

- hooks/001-extra-packages.chroot
snapd-generator will handle /lib/{firmware,modules} mounts on UC24.
> hooks: pull generator from snapd package

- hook-tests/008-etc-writable.test
- hooks/008-etc-writable.chroot
This is not supported by systemd Ubuntu package anymore. It is still created by tzdata, even though it should not be. So we need to remove it.
Fixes #197
> Remove /etc/timezone

- static/usr/lib/tmpfiles.d/journald-conf-d.conf
@bboozzoo as per the suggestion in MM.
This would allow us to be able to grant access to the journald.conf.d directory, allowing customers to create drop-ins and customize the journald experience.
I'll open similar ones for core22/core20 if we agree.
Per @valentindavid suggestion, use tmpfiles.d to create the directory as it won't be created otherwise because of how /etc/systemd is mounted in writable paths.
> static/usr/lib/tmpfiles.d: create journald config drop-in directory

- tests/lib/prepare-utils.sh
The edge model uses the pc-kernel beta. So if we use edge, it will automatically update on first boot.
> tests: use beta branch with edge model

- hooks/000-provide-uids-gids.chroot
- hooks/040-remove-pkgs.chroot
- hooks/990-ensure-uids-gids.chroot
It seems that not having a dhcpcd-base client causes issues with usages of cloud-init. We see this on GCE and in Certifications testing when using the images.
As long as cloud-init is a part of the base, it makes better sense to also contain its dependencies.
For more info see:
https://github.com/snapcore/core-base/pull/186#issuecomment-2018299100
https://github.com/canonical/cloud-init/issues/5088
This can be causing the issue we are seeing in UC related to failing to create users through adduser - as it may be falling back to creating through that if it cannot otherwise resolve other data-sources.
> hooks: do not remove dhcpcd-base

- hooks/001-extra-packages.chroot
- hooks/009-locale-archive.chroot
- tests/lib/external/snapd-testing-tools/tests/repack-kernel/task.yaml
- tests/lib/external/snapd-testing-tools/tools/repack-kernel
- tests/lib/prepare-utils.sh
- tests/spread/ci/build-image/task.yaml
Using apt gives the following warning:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> Replace usage of 'apt' with 'apt-get'

- hooks/014-set-motd.chroot
- snapcraft.yaml
The LP build was broken since the daily images are now ocular. Switch to the correct release images
> snapcraft: switch to release image

- snapcraft.yaml
This bumps probert and subiquity/console-conf to commits that have been relicensed to GPL3-only.
I have built the core22 snap locally with and without this change and the differences are only what is expected.
As the comment change suggests, I have created branched in the subiquity and probert repos to track the commits that go into core22, we could change core22 to follow those branches if that would make things smoother (and you trust us not to mess with them, I guess).
> bump subiquity and probert

- hooks/000-provide-uids-gids.chroot
- hooks/001-extra-packages.chroot
- static/usr/lib/tmpfiles.d/coredump-comf-d.conf
This is a backport of https://github.com/snapcore/core-base/pull/227
> hooks,static: add support for systemd-coredump

- static/usr/lib/core/run-snapd-from-snap
The new FDE manager needs access the kernel keyring to access the primary key. That includes seeding.
> run-snapd-from-snap: seed with access to keyring

- Makefile
- hooks/603-cleanup-docs.chroot
- snapcraft.yaml
- tools/generate-changelog.py
Generates a changelog like we do for system-snaps, just between the dpkg.yaml manifests that we already generate.
The changelog is installed into `/usr/share/doc/ChangeLog` (however this is up to dicussion if you feel like we should do it somewhere else).
This needs to be backported to other core bases once it's approved
> snapcraft,make(core24): add script for generating changelogs, include as part of build

- static/etc/system-image/writable-paths
If dhcpcd is installed in a cloud image, cloud-init may attempt early datasource discovery using dhcpcd in order to get information about active instance metadata service IP addresses and routes. The dhcpcd client writes out leases which cloud-init parses under /var/lib/dhcpcd.
Add this support so cloud-init can detect network-bound datasources such as Azure, Ec2 and GCE.
> writable-paths: add /var/lib/dhcpcd writable-paths for datasource discovery

- hooks/020-extra-files.chroot
- static/etc/system-image/writable-paths
cloud-init persists any configuration data crawled from Azure instance metadata service  or ovf-env.xml files to /var/lib/waagent directory to allow walinux-agent to interact with various early boot configuration seeds. If that directory does not exist or is readonly cloud-init will hit a permissions error resulting in inability to detect the Azure instance metadata service to obtain boot-time cloud-init configuration.
> feat(azure): support cloud-init persistent writes to /var/lib/waagent

- .github/workflows/lxd-image.yaml
- .github/workflows/tests.yaml
- static/etc/system-image/writable-paths
- tests/lib/external/snapd-testing-tools/.github/workflows/tests.yaml
We want to mount /snap and /var/lib/snapd from the initramfs as they are a requisite to mount the kernel snap from initramfs.
> static: mount some directories from initramfs

- Makefile
- fips.conf.example
- hooks/001-extra-packages.chroot
- snapcraft.yaml
- tools/generate-changelog.py
This is a backport of the core24 FIPS PR https://github.com/canonical/core-base/pull/249 .
The major difference here is that we pull the correct core-base to do changelog against for FIPS, and that we use a different PPA.
> core22: add FIPS build support

- hooks/001-extra-packages.chroot
Backport of https://github.com/canonical/core-base/pull/268
> hooks: include nvidia rules only for supported arches

- hooks/001-extra-packages.chroot
Backport of https://github.com/canonical/core-base/pull/273
> hooks: include nvidia modprobe configuration from deb

- static/usr/lib/systemd/system/getty.target.wants/console-conf@tty1.service
dh_installsystemd assumes that template units cannot be enabled. That is not true. Units with DefaultInstance can be enabled. And this is the case for console-conf@service. So instead we manually install it with a symlink.
This should not affect core24 or later.
> console-conf: work around dh_installsystemd not enabling template units

- hooks/001-extra-packages.chroot
- Allow launchpad intenal build access private ppa without credentials
- According to the lp building log:
```
RUN: /usr/share/launchpad-buildd/bin/in-target override-sources-list --backend=lxd --series=noble --arch=amd64 SNAPBUILD-2655127 'deb http://private-ppa.buildd/fips-cc-stig/fips-under-certification/ubuntu noble main' 'deb http://ftpmaster.internal/ubuntu noble main universe' 'deb http://ftpmaster.internal/ubuntu noble-security main universe'
```
The builder **automatically** add "http://private-ppa.buildd" as the source list for current ppa. So I give a shot here to see if this solve the access problem. 
- I also tried to reproduce locally with the launchpad-buildd following the log, the "private-ppa.buildd" and "http://ftpmaster.internal/" failed to resolved as expected and I …
> Add internal source url

- hooks/600-no-debian.chroot
See https://github.com/canonical/core-base/issues/283 and the comment for the change.
I don't think its the right choice for the snapcraft snap to be importing this. On Chisel there will be no apt environment at all, and they cannot even assume any `apt` presence. I think we should file a bug for snapcraft to stop importing this, or atleast make them resistent to this. (See https://github.com/canonical/snapcraft/issues/5146)
> hooks(core22): do not remove libapt for now

- hooks/600-no-debian.chroot
See https://github.com/canonical/core-base/issues/283 and the comment for the change.
I don't think its the right choice for the snapcraft snap to be importing this. On Chisel there will be no apt environment at all, and they cannot even assume any apt presence. Filed a bug for Snapcraft: https://github.com/canonical/snapcraft/issues/5146
> hooks(core24): keep libapt around for now

- hooks/001-extra-packages.chroot
While we fixed the FIPS build, and correctly can access the PPA - it seems I was missing this commit for our upstream version. This uses the correct pinning for FIPS builds.
> hooks: always write the FIPS preference for FIPS builds

- static/usr/lib/systemd/system/console-conf@.service.d/fix.conf
- static/usr/lib/systemd/system/serial-console-conf@.service.d/fix.conf
- static/usr/share/subiquity/console-conf-check-error-fix
This is a quick fix that should be applied to upstream.
24 and main will also need a similar fix.
> console-conf: make exit status 22 not reported as a failure

- Makefile
According to lp build log, the Updates pocket wants to introduce the newer version of systemd which causes the build failure. So this pr remove the Updates pocket
> Remove the Updates pocket to avoid dependency issue

- hooks/001-extra-packages.chroot
- spread.yaml
- tests/lib/nested.sh
- tests/lib/prepare-utils.sh
Some netplan/subiquity dependencies have changed and some python packages are not neded anymore. Get them back as otherwise we might be breaking the API for apps using this base.
> hooks: add back some python dependencies

- spread.yaml
- tests/lib/nested.sh
- tests/lib/prepare-utils.sh
- use the new OVMF code/vars files from noble
- fix image, moving to final release
Backport of tests fixes included in https://github.com/canonical/core-base/pull/303
> tests/lib,spread.yaml: fix tests so they can run in noble

- hooks/026-configure-plymouth.chroot
Previously we were moving, but now in noble Ubuntu-R.ttf was actually a link to Ubuntu[wdth,wght].ttf, so actually a symlink to a non-present file was created. Instead, copy the file that we have now, which will also fix the issue if in the future it becomes a symlink too.
> hooks: copy the desired default font to Plymouth.ttf

- Makefile
- As from the [log](https://i770926049.restricted.launchpadlibrarian.net/770926049/buildlog_snap_ubuntu_jammy_amd64_core22-fips_BUILDING.txt.gz?token=RxnJxZgRRK5Zm3d6MwVKQr17zXmLqzmb) the Makefile will execute command `:: sed -n 's/"jammy"-security/"jammy"-updates/p' /etc/apt/sources.list >> /build/core22/parts/bootstrap/install/etc/apt/sources.list;`
which sed will treat "jammy" as-is so the replacement never happens.
- reason that core22 fail to build while core24 succeed with the same Makefile line:
the image core22 download is: https://cdimage.ubuntu.com/ubuntu-base/jammy/daily/current/jammy-base-amd64.tar.gz which only has jammy and jammy-security (expected)
the image core24 download is: https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.1-base-amd64.tar.g …
> Makefile: remove the quotes around CODENAME and reintroduce jammy-updates

- hook-tests/031-faillock.test
- hooks/900-cleanup-etc-var.chroot
Leave /etc/pam.d empty for Core Desktop to experiment with their own per-snap profiles.
A little info surrounding profile loading, also see the [man-pages](https://manpages.opensuse.org/Tumbleweed/pam-manpages/pam.d.5.en.html)
There are three directories, in which PAM is looking for the service files in the following order:
* /etc/pam.d
* /usr/lib/pam.d
If a file is not found in /etc/pam.d, it will be searched in /usr/lib/pam.d and afterwards in /usr/etc/pam.d. 
Considering this function in the source: https://github.com/linux-pam/linux-pam/blob/37b416c152ed833dcc55c84068c77eb713748d24/libpam/pam_handlers.c#L293 
it looks like this should be no issues
**UPDATE** It turned out that include files from pam.d files do only check in `/etc/pam.d`, which on the surface looks like to be a …
> hooks: move pam.d files into /usr/lib/pam.d

- .github/actions/run-spread-tests/action.yaml
- .github/workflows/tests.yaml
Logs spread failures to Grafana and also updates the snapd-test-tools to permit the use of the same tools used in snapd
> tests: log spread failures to grafana for core24

- hooks/001-extra-packages.chroot
The building log:
```
Preparing to unpack .../base-files_13ubuntu10.2_arm64.deb ...
:: Unpacking base-files (13ubuntu10.2) over (13ubuntu10.1) ...
:: Setting up base-files (13ubuntu10.2) ...
::
:: Configuration file '/etc/issue'
::  ==> Modified (by you or by a script) since installation.
::  ==> Package distributor has shipped an updated version.
::    What would you like to do about it ?  Your options are:
::     Y or I  : install the package maintainer's version
::     N or O  : keep your currently-installed version
::       D     : show the differences between the versions
::       Z     : start a shell to examine the situation
::  The default action is to keep your current version.
:: *** issue (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package base-files (--configure):
:: …
```
> hooks: avoid conffile prompt from installing base-files

- .github/actions/run-spread-tests/action.yaml
- .github/workflows/tests.yaml
Logs spread failures to Grafana and also updates the snapd-test-tools to permit the use of the same tools used in snapd
> tests: log spread failures to grafana

- static/usr/lib/core/run-snapd-from-snap
Now we will mount the snapd snap in /snap/snapd/<revision> on first boot to avoid duplicate mounts. Adapt to this initramfs changes.
> static/run-snapd-from-snap: adapt to new mount place for snapd snap

- hook-tests/031-faillock.test
- hooks/900-cleanup-etc-var.chroot
This broke pam.d profiles that came with snaps since they load using relative paths. Relative paths do not work correctly right now and only expect profiles to exist in /etc/pam.d.
Forward-ported from https://github.com/canonical/core-base/pull/324
> main: revert pam.d workaround

- hook-tests/031-faillock.test
- hooks/900-cleanup-etc-var.chroot
This broke pam.d profiles that came with snaps since they load using relative paths. Relative paths do not work correctly right now and only expect profiles to exist in /etc/pam.d.
> core24: rollback pamd workaround and wait for SRU fix instead

- hooks/001-extra-packages.chroot
- hooks/032-systemd-zram-generator.chroot
This add a swap of compressed ram as /dev/zram0. This can be disabled in the kernel command-line with `systemd.zram=0`.
```
valentin.david@ubuntu:~$ swapon 
NAME       TYPE      SIZE USED PRIO
/dev/zram0 partition   4G   0B  100
valentin.david@ubuntu:~$ 
```
> hooks: add systemd-zram-generator

- hooks/032-move-ssh-config.chroot
We want the symlinks for the ssh service in the systemd distro directory instead of in the admin directory. Previously, these links were copied to /etc/systemd on first boot, which is an issue as these symlinks are new to core24, so when remodeling from 20/22 to 24 they are not copied around as handle-writable-paths sees that the /etc/systemd folder already exists. This change ensures that the links are static and will always be present. This is not a problem when enabling/disabling ssh as for that the services rely on the presence of the /etc/ssh/sshd_not_to_be_run file, and in any case is a step forward in the path of having an empty /etc on installation in the future.
When upgrading core24 to one with this change this should be ok as we simply will have the same links in …
> hooks: move around symlinks for the ssh.socket unit

- hook-tests/008-etc-writable.test
- hook-tests/014-set-motd.test
- hooks/008-etc-writable.chroot
- hooks/014-set-motd.chroot
- static/etc/system-image/writable-paths
- static/usr/lib/motd.d/50-default
Instead of having a symlink in /etc/motd that points to a writable path, put the default motd in /usr/lib/motd.d/50-default file, and add /etc/motd.d to the writable paths. With this
- When remodeling, we will show the message from the new base as it is part of the immutable directories.
- It is still possible to override the default message by creating a file named /etc/motd.d/50-default.
- It is also possible to add messages by creating additional files in /etc/motd.d/ or by adding scripts to /etc/update-motd.d/ as in the past.
Backport of https://github.com/canonical/core-base/pull/332
> many: put default motd in /usr

- hooks/032-move-ssh-config.chroot
- tools/generate-changelog.py
The recent change moving the symlinks enabling ssh.socket to /usr/lib made that
the unit was considered disabled as it was not considered static, although it
was still activated. This was an issue for snapd, that check is the unit is
enabled when changing ssh options. Fix by removing the [Install] section from
the unit.
> hooks: make sure that the ssh.socket unit is enabled

- hook-tests/010-locale-vconsole-symlinks.test
- hooks/010-locale-vconsole-symlinks.chroot
The default shipped /etc/vconsole.conf is a symlink to default/keyboard, which is non-existant in the default setup. The default configuration is just to default to US keymap.
Add a test as my previous testing was obviously insufficient, and this fixes a weird symlink loop that was introduced earlier.
Port of https://github.com/canonical/core-base/pull/334 for main branch
> hooks: write default configuration for vconsole.conf

- .github/workflows/release.yaml
Schedules can run only on the default branch. Add a schedule for core24 for the moment, other bases can be added later.
> .github/workflows/release.yaml: schedule core24 builds

- .github/workflows/release-manual.yaml
- .github/workflows/release.yaml
- hooks/000-provide-uids-gids.chroot
Schedule daily builds for core22 too (this was happening only for core24). Note
that builds happen only if there are changes in the repository or if there
changes in the used debian packages.
Additionally, add new user added from udev package recently.
> .github/workflows/release.yaml: trigger also core22 builds

- .github/workflows/release-manual.yaml
- .github/workflows/tests.yaml
Add action to be able to release manually core22 snaps, in case it is deemed necessary.
> .github/workflows: add release-manual action

- get-version.sh
We have a branch per base in the core-base repository, so we need to differentiate between date tags to avoid repetition. For this, we will add a _$branch suffix to tags.
Here we take that into account when filtering tags in the get-version.sh script.
> get-version.sh: filter by _$branch suffix when looking at tags

- hooks/001-extra-packages.chroot
/usr/bin/ss (iproute2) has removed the dependency on libtirpc3t64. Add it back manually to avoid breaking ABI.
> hooks/001-extra-packages.chroot: add back libtirpc3t64

- static/usr/lib/udev/rules.d/90-ubuntu-core-partitions.rules
Without matching rules in core-base, the device symlinks created in initrd creates device units which core-base's systemd does not what to do with, and are shown as "activating".
> static: copy udev disk rules from core-initrd
